FROM python:3.13-slim

WORKDIR /app

# Instala UV
RUN pip install uv

# Copia dependencias
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev

# Copia código
COPY src ./src

# Comando por defecto
CMD ["uv", "run", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]